[package]
name = "TheBusCmd"
version = "1.4.0"
edition = "2024"
license = "MIT"
readme = "README.md"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
the-bus-telemetry = "3.0.0"
komsi = "0.5.0"

[[bin]]
name = "TheBusInfo"
path = "src/bin/info.rs"
